# Generated by Django 5.1.7 on 2025-03-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField()),
                ('game_id', models.PositiveBigIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('progress', models.CharField(max_length=20)),
            ],
        ),
    ]
